[tool.poetry]
name = "advanced-rag"
version = "0.1.0"
description = ""
authors = ["Unai"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
